###

GET http://127.0.0.1:8080/api/users/username/james

###

POST http://127.0.0.1:8080/api/users
Content-Type: application/json

{
    "name": "james",
    "username": "james",
    "password": "abcdefgh"
}

###
POST http://127.0.0.1:8080/api/users/reset